; PlatformIO — https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = firmware
default_envs = flyclap, flysonar

[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

[env:flyclap]
build_src_filter = -<*> +<flyclap/>

[env:flysonar]
build_src_filter = -<*> +<flysonar/>
